# NumPy 

NumPy (ou Numpy) é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do NumPy como um dos seus principais blocos de construção.

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C. Para obter mais informações sobre por que você deseja usar Arrays em vez de listas, confira esta excelente publicação do [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Nós só aprenderemos os conceitos básicos do NumPy, para começar, precisamos instalá-lo!

## Instruções de instalação

** É altamente recomendável que instale o Python usando a distribuição da Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de Álgebra Linear) se sincronizem com o uso de uma instalação conda. Se você tiver o Anaconda, instale o NumPy acessando seu terminal ou prompt de comando e digite: **

    conda install numpy
    
** Se você não possui Anaconda e não pode instalá-lo, consulte: [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

Numpy possui muitas funções e capacidades incorporadas. Não vamos cobri-los na totalidade, mas, em vez disso, vamos nos concentrar em alguns dos aspectos mais importantes de Numpy: vetores, arrays, matrizes e geração de números. Comecemos por arrays:

# Numpy Arrays

As matrizes de NumPy são a maneira principal de usar Numpy ao longo do curso. Numpy arrays essencialmente vêm de duas formas: vetores e matrizes. Os vetores são estritamente arranjos de 1d e as matrizes são 2d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes numPy.


## Criando NumPy Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [2]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [3]:
np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar Arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones(3)

array([ 1.,  1.,  1.])

In [14]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [15]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [6]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Cria uma matriz identidade

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [20]:
np.random.rand(2)

array([ 0.46634816,  0.13377055])

In [10]:
np.random.rand(5,5)

array([[0.0471816 , 0.15140692, 0.34457879, 0.77136997, 0.9091514 ],
       [0.56605727, 0.49434197, 0.61183011, 0.1270742 , 0.95431242],
       [0.60111216, 0.11944883, 0.20133134, 0.52531241, 0.2201623 ],
       [0.71076698, 0.05123566, 0.07382222, 0.41952171, 0.36647219],
       [0.64371972, 0.88908413, 0.092316  , 0.09119226, 0.08340073]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:

In [11]:
np.random.randn(2)

array([-0.5583602 ,  1.08101723])

In [23]:
np.random.randn(5,5)

array([[-0.87657556,  0.03151182,  0.83685254,  0.47021414,  0.05169247],
       [ 0.12624043, -1.67384753, -0.26116216,  0.54199188,  1.35609602],
       [-1.89332603, -0.53626069,  1.97356854, -0.42423178, -1.44121779],
       [-0.87702313, -1.2751979 ,  0.66739175,  1.6723646 ,  0.26337179],
       [-0.050468  , -0.13342553,  0.16537819,  0.02001319,  0.14597014]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [24]:
np.random.randint(1,100)

98

In [12]:
np.random.randint(1,100,10)

array([57, 56,  8, 59, 60, 70, 48, 55, 15, 45])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([36, 23, 46,  4,  5,  9, 12,  5,  8, 23])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [30]:
ranarr

array([36, 23, 46,  4,  5,  9, 12,  5,  8, 23])

In [31]:
ranarr.max()

46

In [32]:
ranarr.argmax()

2

In [33]:
ranarr.min()

4

In [34]:
ranarr.argmin()

3

## Shape

Shape é um atributo que os arrays têm (não um método):

In [35]:
# Vector
arr.shape

(25,)

In [36]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Você também pode pegar o tipo de dados do objeto na matriz:

In [40]:
arr.dtype

dtype('int32')